name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [win, linux, mac]

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --build-arg PLATFORM=${{ matrix.platform }} --file Dockerfile --tag mercury-browser-builder:${{ matrix.platform }}-$(date +%s)
